[package]
name = "nexus-host"
version = "0.1.0"
edition = "2021"

[dependencies]
nexus-sdk = { git = "https://github.com/nexus-xyz/nexus-zkvm", tag = "v0.3.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

[workspace]
members = ["src/guest"]
