[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
nexus-rt = { git = "https://github.com/nexus-xyz/nexus-zkvm", tag = "v0.3.1" }
postcard = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
